web3_verify:
    path: /web3_verify/{address}
    controller: Karhal\Web3ConnectBundle\Controller\Web3ConnectController::verify

web3_nonce:
    path: /web3_nonce/{address}
    controller: Karhal\Web3ConnectBundle\Controller\Web3ConnectController::nonce
