web3_verify:
    path: /web3_verify
    controller: Karhal\Web3ConnectBundle\Controller\Web3ConnectController::verify

web3_nonce:
    path: /web3_nonce
    controller: Karhal\Web3ConnectBundle\Controller\Web3ConnectController::nonce
